src/blog/urls.py
from django.conf.urls.defaults import *
from blog import views

urlpatterns = patterns('blog.views',
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{1,2})/(?P<slug>[-\w]+)/$',
        views.PostDetailView.as_view(), name='blog_detail'
    ),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{1,2})/$',
        views.PostDayArchiveView.as_view(), name='blog_archive_day'
    ),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/$',
        views.PostMonthArchiveView.as_view(), name='blog_archive_month'
    ),
    url(r'^(?P<year>\d{4})/$', views.PostYearArchiveView.as_view(),
        name='blog_archive_year'),
    url(r'^categories/(?P<slug>[-\w]+)/$',
        views.CategoryPostsListView.as_view(), name='blog_category_detail'
    ),
    url (r'^categories/$', views.CategoryListView.as_view(),
        name='blog_category_list'
    ),
    url(r'^tags/(?P<slug>[-\w]+)/$', views.TagPostsListView.as_view(),
        name='blog_tag_detail'
    ),
    url(r'^$', views.PostListView.as_view(),
        name='blog_index'),
    url(r'^page/(?P<page>\d+)/$', views.PostListView.as_view(),
        name='blog_index_paginated'),
)

src/urls.py
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.conf import settings
from feeds import BlogPostsFeed
from django.contrib import admin
admin.autodiscover()

# patterns for contrib modules
urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
)
# blog urls
urlpatterns += patterns('',
    (r'^', include('blog.urls')),
    (r'^photos/', include('media.urls.photos')),
    url(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
        {'feed_dict': {'posts' : BlogPostsFeed}}
    ),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/asset_includes/models.py
from django.db import models
from blog.models import Post 

class Asset(models.Model):
    asset_location = models.TextField(blank=False)
    weight = models.IntegerField(blank=False, default=1)
    posts = models.ManyToManyField(Post)

    class Meta:
        ordering = ['weight']

src/blog/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db.models import permalink
from django.contrib.auth.models import User
from django.conf import settings

from blog.managers import PublicManager

import datetime
import tagging
from tagging.fields import TagField


class Category(models.Model):
    """Category model."""
    title = models.CharField(_('title'), max_length=100)
    slug = models.SlugField(_('slug'), unique=True)

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')
        db_table = 'blog_categories'
        ordering = ('title',)

    def __unicode__(self):
        return u'%s' % self.title

    @permalink
    def get_absolute_url(self):
        return ('blog_category_detail', None, {'slug': self.slug})


class Post(models.Model):
    """Post model."""
    STATUS_CHOICES = (
        (1, _('Draft')),
        (2, _('Public')),
    )
    title = models.CharField(_('title'), max_length=200)
    slug = models.SlugField(_('slug'), unique_for_date='publish')
    author = models.ForeignKey(User, blank=True, null=True)
    body = models.TextField(_('body'), )
    tease = models.TextField(_('tease'), blank=True, help_text=_('Concise text suggested. Does not appear in RSS feed.'))
    status = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=2)
    allow_comments = models.BooleanField(_('allow comments'), default=True)
    publish = models.DateTimeField(_('publish'), default=datetime.datetime.now)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    categories = models.ManyToManyField(Category, blank=True)
    tags = TagField()
    objects = PublicManager()

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        db_table  = 'blog_posts'
        ordering  = ('-publish',)
        get_latest_by = 'publish'

    def __unicode__(self):
        return u'%s' % self.title

    @permalink
    def get_absolute_url(self):
        return ('blog_detail', None, {
            'year': self.publish.year,
            'month': self.publish.strftime('%b').lower(),
            'day': self.publish.day,
            'slug': self.slug
        })

    def get_previous_post(self):
        return self.get_previous_by_publish(status__gte=2)

    def get_next_post(self):
        return self.get_next_by_publish(status__gte=2)


class BlogRoll(models.Model):
    """Other blogs you follow."""
    name = models.CharField(max_length=100)
    url = models.URLField(verify_exists=False)
    sort_order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('sort_order', 'name',)
        verbose_name = _('blog roll')
        verbose_name_plural = _('blog roll')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return self.url

src/blog/views.py
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.views.generic import dates
from django.conf import settings

from blog.models import Post, Category
from tagging.models import Tag, TaggedItem

class PostListView(ListView):
    queryset=Post.objects.published()
    paginate_by=getattr(settings,'BLOG_PAGESIZE', 20)

class PostYearArchiveView(dates.YearArchiveView):
    queryset=Post.objects.published()
    date_field='publish'
    make_object_list=True

class PostMonthArchiveView(dates.MonthArchiveView):
    queryset=Post.objects.published()
    date_field='publish'
    make_object_list=True

class PostDayArchiveView(dates.DayArchiveView):
    queryset=Post.objects.published()
    date_field='publish'
    make_object_list=True

class PostDetailView(dates.DateDetailView):
    date_field='publish'
    def get_queryset(self):
        if self.request.user.is_superuser:
            return Post.objects.all()
        else:
            return Post.objects.published()

class CategoryListView(ListView):
    queryset=Category.objects.all()

class CategoryPostsListView(ListView):
    template_name = 'blog/category_detail.html'

    def get_context_data(self, **kwargs):
        context = super(
            CategoryPostsListView, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context

    def get_queryset(self):
        slug = self.kwargs['slug']
        self.category = get_object_or_404(Category, slug__iexact=slug)
        return self.category.post_set.published()

class TagPostsListView(ListView):
    template_name = 'blog/tag_detail.html'

    def get_context_data(self, **kwargs):
        context = super(
            CategoryPostsListView, self).get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

    def get_queryset(self):
        slug = self.kwargs['slug']
        self.tag = get_object_or_404(Tag, name__iexact=slug)
        return TaggedItem.objects.get_by_model(Post,tag).filter(status=2)

src/blog/templates/blog/base_blog.html
{% extends "base.html" %}


{% block body_class %}blog{% endblock %}

src/blog/templates/blog/category_detail.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Posts for" %} {{ category.title }}{% endblock %}
{% block body_class %}{{ block.super }} category_detail{% endblock %}
{% block body_id %}category_{{ category.id }}{% endblock %}


{% block content_title %}
  <h2>{% trans "Posts for" %} {{ category.title }}</h2>
{% endblock %}


{% block content %}
  <div class="post_list">
    {% for post in object_list %}
    <div>
      <h3 class="title"><a href="{{ post.get_absolute_url }}" title="{% trans "View this post" %}">{{ post.title }}</a></h3>
      <p class="date">{{ post.publish|date:"Y F d" }}</p>
      <p class="tease">{{ post.body|safe }}</p>
      {% if post.tease %}
        <a href="{{ post.get_absolute_url }}" title="{% trans "Link to this post" %}">Read more...</a>
      {% endif %}
    </div>
    {% endfor %}
  </div>
{% endblock %}

src/blog/templates/blog/category_list.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post categories" %}{% endblock %}
{% block body_class %}{{ block.super }} category_list{% endblock %}


{% block content_title %}
  <h2>{% trans "Post categories" %}</h2>
{% endblock %}


{% block content %}
  <ul class="link_list">
    {% for category in object_list %}
    <li><a href="{{ category.get_absolute_url }}" title="{% trans "View posts in this category" %}">{{ category }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

src/blog/templates/blog/post_archive_day.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post archive for" %} {{ day|date:"d F Y" }}{% endblock %}
{% block body_class %}{{ block.super }} post_archive_day{% endblock %}


{% block content_title %}
  <h2>{% trans "Post archive for" %} {{ day|date:"d F Y" }}</h2>
{% endblock %}


{% block content %}
  <div class="post_list">
    {% for post in object_list %}
    <div>
      <h3 class="title"><a href="{{ post.get_absolute_url }}" title="{% trans "View this post" %}">{{ post.title }}</a></h3>
      <p class="date">{{ post.publish|date:"Y F d" }}</p>
      <p class="tease">{{ post.tease|safe }}</p>
    </div>
    {% endfor %}
  </div>
{% endblock %}

src/blog/templates/blog/post_archive_month.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post archive for" %} {{ month|date:"F Y" }}{% endblock %}
{% block body_class %}{{ block.super }} post_archive_month{% endblock %}


{% block content_title %}
  <h2>{% trans "Post archive for" %} {{ month|date:"F Y" }}</h2>
{% endblock %}


{% block content %}
  <div class="post_list">
    {% for post in object_list %}
    <div>
      <h3 class="title"><a href="{{ post.get_absolute_url }}" title="{% trans "View this post" %}">{{ post.title }}</a></h3>
      <p class="date">{{ post.publish|date:"Y F d" }}</p>
      <p class="tease">{{ post.tease|safe }}</p>
    </div>
    {% endfor %}
  </div>
{% endblock %}

src/blog/templates/blog/post_archive_year.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post archive for" %} {{ year }}{% endblock %}
{% block body_class %}{{ block.super }} post_archive_year{% endblock %}


{% block content_title %}
  <h2>{% trans "Post archive for" %} {{ year }}</h2>
{% endblock %}


{% block content %}  
  <ul class="link_list">
    {% for month in date_list %}
    <li><a href="{% url blog_index %}{{ year }}/{{ month|date:"b" }}/" title="{% trans "View items posted this month" %}">{{ month|date:"F" }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

src/blog/templates/blog/post_detail.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block css %}
  <link href="/syntax/shCoreDefault.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block javascript %}
  {% for asset in object.asset_set.all %}
  <script type="text/javascript" src="/syntax/{{asset.asset_location}}"></script>
  {% endfor %}
  <script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load("jquery", "1");
    google.setOnLoadCallback(function() {});
  </script>
  <script type="text/javascript">SyntaxHighlighter.all();</script>
{% endblock %}

{% block title %}{{ object.title }}{% endblock %}
{% block body_class %}{{ block.super }} post_detail{% endblock %}
{% block body_id %}post_{{ object.id }}{% endblock %}


{% block content_title %}
{% endblock %}


{% block content %}
  {% load blog comments markup i18n %}
  <p class="other_posts">
    {% if object.get_previous_by_publish %}
    <a class="previous" href="{{ object.get_previous_post.get_absolute_url }}" title="{% trans "View previous post" %}">&laquo; {{ object.get_previous_post }}</a>
    {% endif %}
    {% if object.get_next_by_publish %}
    | <a class="next" href="{{ object.get_next_post.get_absolute_url }}" title="{% trans "View next post" %}">{{ object.get_next_post }} &raquo;</a>
    {% endif %}
  </p>

  {% load blog tagging_tags inlines markup i18n %}
  <h3 class="blogPostTitle">
    <a href="{{ object.get_absolute_url }}" title="{% trans "Link to this post" %}">
        {{ object.title }}
    </a>
  </h3>

  <div class="blogPostDate">{{ object.publish|date:"j F Y" }}</div>

  <div class="body">
    {{ object.body|render_inlines|safe }}
    {{ object.tease|render_inlines|safe }}
  </div>

  {% tags_for_object object as tag_list %}
  {% if tag_list %}
  <p class="inline_tag_list"><strong>{% trans "Related tags" %}:</strong>
    {{ tag_list|join:", " }}
  </p>
  {% endif %}

  {% get_comment_list for object as comment_list %}
  {% if comment_list %}
  <div id="comments">
    <a name="comments"></a>
    <h3 class="commentsTitle">{% trans "Comments" %}</h3>
    {% for comment in comment_list %}
      {% if comment.is_public %}
      <div class="comment">
        <h5 class="name">
          <a name="c{{ comment.id }}" href="{{ comment.get_absolute_url }}" title="{% trans "Permalink to" %} {% blocktrans with comment.user_name as user_name %}{{ user_name }}'s{% endblocktrans %} {% trans "comment" %}" class="count">{{ forloop.counter }}</a>
          {% if comment.user_url %}
            <a href="{{ comment.user_url }}" title="{% trans "View" %} {% blocktrans with comment.user_name as user_name %}{{ user_name }}'s{% endblocktrans %} {% trans "website" %}">{{ comment.user_name }}</a>
          {% else %}
            {{ comment.user_name }}
          {% endif %}
          {% trans "says" %}...
        </h5>
        {{ comment.comment|striptags|urlizetrunc:"60"|markdown }}
        <p class="date">{% trans "Posted at" %} {{ comment.submit_date|date:"P" }} {% trans "on" %} {{ comment.submit_date|date:"F j, Y" }}</p>
      </div>
      {% endif %}
    {% endfor %}
  </div>
  {% endif %}
  {% if object.allow_comments %}
    <div id="commentForm">
      <p>You can format comments using <a href="http://daringfireball.net/projects/markdown/syntax">Markdown</a> syntax.</p>
      {% render_comment_form for object %}
    </div>
  {% else %}
    <div id="comment_form">
      <h3>{% trans "Comments are closed" %}.</h3>
      <p>{% trans "Comments have been closed for this post" %}.</p>
    </div>
  {% endif %}
{% endblock %}

src/blog/templates/blog/post_list.html
{% extends "blog/base_blog.html" %}

{% load i18n tagging_tags inlines markup %}


{% block title %}Ragtag blog{% endblock %}
{% block body_class %}{{ block.super }} post_list{% endblock %}


{% block content_title %}

{% endblock %}


{% block content %}
  <div class="list post_list">
    {% for object in object_list %}
        <div class="item">
            {% load blog tagging_tags inlines markup i18n %}
            <h3 class="blogPostTitle">
              <a href="{{ object.get_absolute_url }}" title="{% trans "Link to this post" %}">
                  {{ object.title }}
              </a>
            </h3>

            <div class="blogPostDate">{{ object.publish|date:"j F Y" }}</div>

            <div class="tease">
              {{ object.body|render_inlines|safe }}
            </div>

            {% if object.tease %}
              <a href="{{ object.get_absolute_url }}" title="{% trans "Link to this post" %}">Read more...</a>
            {% endif %}
        </div>
    {% endfor %}

  </div>

  {% if is_paginated %}
  <p class="pagination">
    {% if has_next %}
    <a class="older" href="?page={{ next }}" title="{% trans "View older posts" %}">{% trans "Older" %}</a>
    {% endif %}
    {% if has_next and has_previous %} | {% endif %}
    {% if has_previous %}
    <a class="newer" href="?page={{ previous }}" title="{% trans "View newer posts" %}">{% trans "Newer" %}</a>
    {% endif %}
  </p>
  {% endif %}
{% endblock %}

src/blog/templates/blog/post_search.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post search" %}{% endblock %}
{% block body_class %}{{ block.super }} post_search{% endblock %}


{% block content_title %}
  <h2>{% trans "Search" %}</h2>
{% endblock %}


{% block content %}
  <form action="." method="get" id="post_search_form">
    <p>
      <input type="text" name="q" value="{{ search_term }}" id="search">
      <input type="submit" class="button" value="{% trans "Search" %}">
    </p>
  </form>
  
  {% if message %}
  <p class="message">{{ message }}</p>
  {% endif %}
  
  {% if object_list %}
  <div class="post_list">
    {% for post in object_list %}
    <div>
      <h3 class="title"><a href="{{ post.get_absolute_url }}" title="{% trans "View this post" %}">{{ post.title }}</a></h3>
      <p class="date">{{ post.publish|date:"Y F d" }}</p>
      <p class="tease">{{ post.tease|safe }}</p>
      <p class="comments">{% if comment_count %}{{ comment_count }} {% blocktrans with comment_count|pluralize as pluralize %}comment{{ pluralize }}{% endblocktrans %}{% endif %}</p>
    </div>
    {% endfor %}
  </div>
  {% endif %}
{% endblock %}

src/blog/templates/blog/tag_detail.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Posts for" %} {{ tag.name }}{% endblock %}
{% block body_class %}{{ block.super }} tag_detail{% endblock %}
{% block body_id %}tag_{{ tag.id }}{% endblock %}


{% block content_title %}
  <h2>{% trans "Posts for" %} {{ tag.name }}</h2>
{% endblock %}


{% block content %}
  <div class="post_list">
    {% for post in object_list %}
    <div>
      <h3 class="title"><a href="{{ post.get_absolute_url }}" title="{% trans "View this post" %}">{{ post.title }}</a></h3>
      <p class="date">{{ post.publish|date:"Y F d" }}</p>
      <p class="tease">{{ post.tease|safe }}</p>
    </div>
    {% endfor %}
  </div>
{% endblock %}

src/blog/templates/blog/tag_list.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post tags" %}{% endblock %}
{% block body_class %}{{ block.super }} tag_list{% endblock %}


{% block content_title %}
  <h2>{% trans "Post tags" %}</h2>
{% endblock %}


{% block content %}
  <ul class="link_list">
    {% for tag in object_list %}
    <li><a href="{{ tag.get_absolute_url }}" title="{% trans "View posts tagged" %} {{ tag }}">{{ tag }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}